#!/usr/bin/env python3
# Copyright 2024 Stu Teasdale
# Redistribution and use in source and binary forms, with or without modification, are permitted
# under the conditions specified in the LICENSE file.

from paranoialib.character import Character

char=Character()

char.printCharacter()
